CREATE TABLE IF NOT EXISTS `widgets` (
	`id`	TEXT NOT NULL UNIQUE,
	`width`	INTEGER NOT NULL DEFAULT 300,
	`height`	INTEGER NOT NULL DEFAULT 300,
	`url`	TEXT NOT NULL,
	`content`	TEXT NOT NULL DEFAULT '',
	PRIMARY KEY(`id`)
);
