CREATE TABLE IF NOT EXISTS `widgets` (
	`id`	TEXT NOT NULL UNIQUE,
	`width`	INTEGER NOT NULL DEFAULT 300 CHECK(width > 0),
	`height`	INTEGER NOT NULL DEFAULT 300 CHECK(height > 0),
	`url`	TEXT NOT NULL CHECK(url <> ''),
	`content`	TEXT NOT NULL DEFAULT '',
	PRIMARY KEY(`id`)
);
